In [1]:
#Series (1D Data)
import pandas as pd

s = pd.Series([10, 20, 30])
print(s)

0    10
1    20
2    30
dtype: int64

In [2]:
#DataFrame (Table / 2D Data)
data={
    "Name":["A","B","C"],
    "Marks":[80,90,70]
}
df=pd.DataFrame(data)
print(df)

  Name  Marks
0    A     80
1    B     90
2    C     70

In [4]:
#Load Data
df = pd.read_csv("data.csv")

In [6]:
#View Data
df.head()      # first 5 rows

     Name  Age  Marks
0  Sakshi   20     85
1   Rahul   22     78
2    Amit   21     90
3   Priya   23     88
4    Neha   20     76

In [7]:
df.tail()      # last 5 rows

     Name  Age  Marks
0  Sakshi   20     85
1   Rahul   22     78
2    Amit   21     90
3   Priya   23     88
4    Neha   20     76

In [8]:
df.info()      # structure

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

In [9]:
df.describe()  # statistics

            Age     Marks
count   5.00000   5.00000
mean   21.20000  83.40000
std     1.30384   6.14817
min    20.00000  76.00000
25%    20.00000  78.00000
50%    21.00000  85.00000
75%    22.00000  88.00000
max    23.00000  90.00000

In [10]:
#Select Data
df["Marks"]
df[["Name","Marks"]]

     Name  Marks
0  Sakshi     85
1   Rahul     78
2    Amit     90
3   Priya     88
4    Neha     76