In [1]:
#Series (1D Data)
import pandas as pd

s = pd.Series([10, 20, 30])
print(s)

0    10
1    20
2    30
dtype: int64

In [2]:
#DataFrame (Table / 2D Data)
data={
    "Name":["A","B","C"],
    "Marks":[80,90,70]
}
df=pd.DataFrame(data)
print(df)

  Name  Marks
0    A     80
1    B     90
2    C     70

In [4]:
#Load Data
df = pd.read_csv("data.csv")

In [6]:
#View Data
df.head()      # first 5 rows

     Name  Age  Marks
0  Sakshi   20     85
1   Rahul   22     78
2    Amit   21     90
3   Priya   23     88
4    Neha   20     76

In [7]:
df.tail()      # last 5 rows

     Name  Age  Marks
0  Sakshi   20     85
1   Rahul   22     78
2    Amit   21     90
3   Priya   23     88
4    Neha   20     76