In [1]:
#create data
import pandas as pd
import numpy as np

data = {
    "Name": ["A", "B", "C", "D"],
    "Marks": [80, np.nan, 90, None],
    "Age": [20, 21, None, 22]
}

df = pd.DataFrame(data)
print(df)

  Name  Marks   Age
0    A   80.0  20.0
1    B    NaN  21.0
2    C   90.0   NaN
3    D    NaN  22.0

In [2]:
#Check Missing Values
print(df.isnull())        # shows True/False

    Name  Marks    Age
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True  False

In [3]:
#missing value
print(df.isnull().sum())  # count missing

Name     0
Marks    2
Age      1
dtype: int64

In [4]:
#remove missing values
df.dropna()

  Name  Marks   Age
0    A   80.0  20.0

In [5]:
#Remove columns
df.dropna(axis=1)

  Name
0    A
1    B
2    C
3    D

In [6]:
#fill missing values with 0
df.fillna(0,inplace=True)

  Name  Marks   Age
0    A   80.0  20.0
1    B    0.0  21.0
2    C   90.0   0.0
3    D    0.0  22.0

In [9]:
#fill missing values with mean
df["Marks"].fillna(df["Marks"].mean(),inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_15640\1497318744.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Marks"].fillna(df["Marks"].mean(),inplace=True)

0    80.0
1     0.0
2    90.0
3     0.0
Name: Marks, dtype: float64

In [10]:
#fill missing values with median
df["Age"].fillna(df["Marks"].mean(),inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_15640\1217844063.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Age"].fillna(df["Marks"].mean(),inplace=True)

0    20.0
1    21.0
2     0.0
3    22.0
Name: Age, dtype: float64

In [11]:
#fill missing value with Specific Value
df["Age"].fillna(21,inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_15640\2136364782.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Age"].fillna(21,inplace=True)

0    20.0
1    21.0
2     0.0
3    22.0
Name: Age, dtype: float64