In [1]:
#create data
import pandas as pd
import numpy as np

data = {
    "Name": ["A", "B", "C", "D"],
    "Marks": [80, np.nan, 90, None],
    "Age": [20, 21, None, 22]
}

df = pd.DataFrame(data)
print(df)

  Name  Marks   Age
0    A   80.0  20.0
1    B    NaN  21.0
2    C   90.0   NaN
3    D    NaN  22.0

In [2]:
#Check Missing Values
print(df.isnull())        # shows True/False

    Name  Marks    Age
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True  False

In [3]:
#missing value
print(df.isnull().sum())  # count missing

Name     0
Marks    2
Age      1
dtype: int64

In [4]:
#remove missing values
df.dropna()

  Name  Marks   Age
0    A   80.0  20.0

In [5]:
#Remove columns
df.dropna(axis=1)

  Name
0    A
1    B
2    C
3    D